=== artnavsegda/wjnavsegda/src/json/mobile.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Mobile",
  "description": "Interface list",
  "type": "array",
  "items": {
    "type": "object",
    "title": "Interface entity",
    "required": ["name"],
    "properties": {
      "name": {
        "type": "string",
        "description": "Interface name"
      },
      "enable": {
        "type": "boolean",
        "description": "Enable cellulare interface"
      },
      "apn": {
        "type": "string",
        "description": "Access point name",
        "command": "uci set network.%n.%s=%v"
      },
      "username": {
        "type": "string",
        "description": "Username"
      },
      "password": {
        "type": "string",
        "description": "Password"
      },
      "mode": {
        "type": "string",
        "enum": ["auto","edge","umts","lte"],
        "description": "Network access mode"
      },
      "bands": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "type": "string",
          "enum": ["850","900","1800","1900","2100","2600"],
          "description": "Freq bands allowed"
        }
      }
    }
  }
}

=== artnavsegda/wjnavsegda/src/json/mobile.json
[
            {
                "name":         "sim1",
                "apn":          "internet.mtt.ru",
                "username":     "vpn11930",
                "password":     "kHye%@09nnBSA",
                "mode":         "auto",
                "enable":       true
            },
            {
                "name":         "sim2",
                "apn":          "vpnapn.msk.by",
                "username":     "user9234729",
                "password":     "0912hbjahse6898ryfha",
                "mode":         "lte",
                "enable":       true
            }
]
